---
driver:
  name: docker

platforms:
  - name: centos-6.6
    run_list: 'recipe[docker-integration-test]'

suites:
  - name: docker-integration-test
    run_list:
      - 'recipe[docker-integration-test]'
