---
driver:
  name: docker
  # use_sudo: false

platforms:
  - name: centos-6.6
    run_list: 'recipe[docker-integration-test]'
    # driver_config:
    #   image: 420ma/centos-chef
    #   platform: centos
    #   require_chef_omnibus: true

# suites:
#   - name: docker-integration-test
#     run_list:
#       - 'recipe[docker-integration-test]'
