---
driver:
  name: docker
  privileged: true

platforms:
  - name: <%= ENV['PLATFORM'] || centos-6 %>

suites:
  - name: docker-integration-test
    run_list:
      - 'recipe[docker-integration-test]'
