sudo: required

services:
  - docker

language: ruby

cache: bundler
bundler_args: --without development

env:
  global:
    - KITCHEN_YAML=.kitchen.travis.yml
  matrix:
    - PLATFORM=centos-6
    - PLATFORM=centos-7

script:
  - travis_retry bundle exec rake travis
