sudo: required

services:
  - docker

language: ruby

cache: bundler
bundler_args: --without development

script:
  - export KITCHEN_YAML=.kitchen.docker.yml
  - export KITCHEN_LOCAL_YAML=.kitchen.docker.yml
  - travis_retry bundle exec rake travis
