before_install:
  - git submodule update --init --recursive
bundler_args: --without development
language: ruby
rvm:
  - 2.3.1

sudo: true

before_script:
  - source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.4.0/scripts/start_docker.sh)

script:
  - travis_retry bundle exec rake integration:docker
  # - bundle exec rake travis
  # - KITCHEN_LOCAL_YAML=.kitchen.docker.yml bundle exec kitchen test

after_failure: cat docker_daemon.log
